version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # ESP-IDF Components
  - package-ecosystem: "idf"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
