idf_component_register(
    SRCS
        "main.c"
        "wifi_manager.c"
        "storage_manager.c"
        "display/lv_port_disp.c"
        "display/backlight_manager.c"
        "ui/lvgl_widgets.c"
        "ui/pet_anim.c"
        "ui/pet_ui.c"
        "ui/wifi_ui.c"
        "ui/sprite_pet.c"
        "ui/buddy/buddy_ui.c"
        "ui/buddy/buddy_anim.c"
        "comm/uart_comm.c"
        "comm/tcp_server.c"
        "comm/sntp_sync.c"
        "comm/xfer.c"
        "battery/battery_monitor.c"
        "input/lvgl_touch.c"
        "buddy/buddy_state.c"
        "buddy/buddy_stats.c"
    INCLUDE_DIRS
        "."
        "display"
        "ui"
        "ui/buddy"
        "comm"
        "input"
        "buddy"
        "battery"
    PRIV_REQUIRES
        driver
        esp_driver_ledc
        esp_driver_usb_serial_jtag
        esp_lcd
        cjson
        lvgl
        i2c_bsp
        esp_timer
        esp_wifi
        nvs_flash
        esp_netif
        lwip
        littlefs
        mbedtls
        esp_adc
)
