idf_component_register(
    SRCS
        "main.c"
        "wifi_manager.c"
        "display/lv_port_disp.c"
        "ui/lvgl_chat_ui.c"
        "ui/lvgl_widgets.c"
        "comm/uart_comm.c"
        "input/lvgl_touch.c"
    INCLUDE_DIRS
        "."
        "display"
        "ui"
        "comm"
        "input"
    PRIV_REQUIRES
        driver
        esp_lcd
        json
        lvgl
        i2c_bsp
        esp_timer
        esp_wifi
        nvs_flash
        esp_netif
)
